cards:
  - image: /uploads/tide-magazine-sailing-lifestyle-travel-issue11-environment-5.jpg
    alt: 'A Letter from Norway '
    link: /articles/letter-from-norway
    tags:
      - Environment
      - number 11
    title: 'A Letter from Norway '
    description: ' The Nordic country’s dramatic fjords are a major drawcard for the millions who travel to see the local landscape each year. We explore how the uniquely wild water wonders are currently being future-proofed '
  - image: >-
      /uploads/tide-magazine-sailing-lifestyle-travel-issue10-environment-1-1.jpg
    alt: ' Evolving Modernism '
    link: /articles/pianosa
    tags:
      - Environment
      - number 10
    title: ' The Force Of Nature '
    description: ' After centuries of being both fought over and neglected, today the tiny isle of Pianosa has become a precious international case in the promising power of rewilding. We investigate how such an evolution came about '
  - image: >-
      /uploads/tide-magazine-sailing-lifestyle-travel-issue09-environment-seatrees-1.jpg
    alt: ' Life in the Meadows '
    link: /articles/sea-trees
    tags:
      - 'Environment '
      - number 09
    title: ' Life in the Meadows '
    description: ' Seagrass meadows, among the oldest life on earth, are our secret weapon in fighting climate change. But these hidden forests are under threat. Luckily, a Mallorcan project is diving in to help save them '
  - image: /uploads/tide-magazine-sailing-lifestyle-travel-issue08-environment-1.jpg
    alt: ' Atoll Protected '
    link: /articles/atoll-protected
    tags:
      - 'Environment '
      - number 08
    title: ' Atoll Protected '
    description: ' As it undertakes its mission to conserve the islet’s special environment and culture, the hard-working Teti’aroa Society has also sketched out a pathway for the restoration of oceanic islands in general '
content_on_image:
  image: /images/tide-banner2.png
  alt: TIDE's Top Ten Sailing Destinations
  tags:
    - Travel
    - Number 11
  title: TIDE's Top Ten Sailing Destinations
  description: >-
    For decades, sailors have set a course for the Cyclades, but not only for
    its myriad cultural attractions, sandy beaches, hidden coves and gin-clear
    seas.
  button:
    text: More
    link: /destinations
    class: width-fit btn white-btn
featured_section:
  cards:
    - image: /images/sailing-stockholm.png
      alt: Sailing Stockholm
      link: /articles/itinerary-cuba
      tags:
        - Travel
        - Number 11
      title: 'Checking In: Petunia Hotel, Ibiza'
      description: >-
        With a growing number of smart eco-focused stays across the Finnish
        archipelago, this little-known part of the world is having...
    - image: /images/Three-a-Charm.png
      alt: Three's a Charm
      link: /articles/itinerary-cuba
      tags:
        - Travel
        - Number 11
      title: La Dolce Vita Itinerary
      description: >-
        The day Marie-Louise Sciò first set foot on the island of Ischia in 2018
        and breathed in the jasmine and wild thyme-fragranced...
    - image: /images/sailing-stockholm.png
      alt: Sailing Stockholm
      link: /articles/itinerary-cuba
      tags:
        - Travel
        - Number 11
      title: Nilaya Rises
      description: >-
        The day Marie-Louise Sciò first set foot on the island of Ischia in 2018
        and breathed in the jasmine and wild thyme-fragranced...
    - image: /images/Three-a-Charm.png
      alt: Three's a Charm
      link: /articles/itinerary-cuba
      tags:
        - Travel
        - Number 11
      title: Three's a Charm
      description: >-
        The day Marie-Louise Sciò first set foot on the island of Ischia in 2018
        and breathed in the jasmine and wild thyme-fragranced...
cards2:
  - image: /images/sailing-stockholm.png
    alt: Sailing Stockholm
    link: /articles/itinerary-cuba
    tags:
      - Travel
      - Number 11
    title: Sailing Stockholm
    description: The North American island nation...
  - image: /images/Three-a-Charm.png
    alt: Three's a Charm
    link: /articles/itinerary-cuba
    tags:
      - Travel
      - Number 11
    title: Three's a Charm
    description: The day Marie-Louise Sciò...
subscribe_section:
  left_image: /images/magazine.png
  right_image: /images/tablet.png
  title: Subscribe
  buttons:
    - text: IN PRINT
      class: btn-border
      arrow: left
    - text: DIGITAL
      class: btn-border
      arrow: right
